id: P005498
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:54:50.514602
source_metadata:
  id: bdr:W1AC362
  title: 'ཆབ་མདོའི་བྲོ་ཆེན། '
  author: ''
  volumes:
    45696fe040b347bb8bc51cb8dd1479e2:
      image_group_id: I4PD4488
      title: ''
      volume_number: 1
      total_pages: 270
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
