id: P005498
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC362
  title: 'ཆབ་མདོའི་བྲོ་ཆེན། '
  author: ''
  volumes:
    45696fe040b347bb8bc51cb8dd1479e2:
      image_group_id: I4PD4488
      title: ''
      volume_number: 1
      total_pages: 270
