id: I8A0157AA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T02:26:26+00:00'
last_modified: '2022-06-08T03:30:52.125616+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC362
  title: 'ཆབ་མདོའི་བྲོ་ཆེན། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AC04:
      image_group_id: I4PD4488
      title: ''
      total_pages: 270
      order: 1
      base_file: AC04.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
